const actions = {
    INCREMENT_SESSION: 'INCREMENT_SESSION',
    DECREMENT_SESSION: 'DECREMENT_SESSION',
    UPDATE_SESSION: 'UPDATE_SESSION',
    INCREMENT_BREAK: 'INCREMENT_BREAK',
    DECREMENT_BREAK: 'DECREMENT_BREAK',
    UPDATE_BREAK: 'UPDATE_BREAK',
    START_TIMER: 'START_TIMER',
    STOP_TIMER: 'STOP_TIMER',
    RESET_TIMER: 'RESET_TIMER',
    DECREMENT_TIMER: 'DECREMENT_TIMER',
    SWITCH_TO_BREAK_PHASE: 'SWITCH_TO_BREAK_PHASE',
    SWITCH_TO_SESSION_PHASE: 'SWITCH_TO_SESSION_PHASE',
    UPDATE_STYLE: 'UPDATE_STYLE',
};

export default actions;
